first-iteration stat_svc
koalannette/java-explore-with-me pull request #3
Opened 2023-09-15 01:11 UTC by koalannette

2023-09-16 19:22 UTC, z8q requested changes

2023-09-16 19:22 UTC, z8q commented on stats/client/src/main/java/ru/practicum/stats_client/StatsClient.java
> +                .timestamp(timestamp)
timestamp можно задавать LocalDateTime.now() – текущее время
app можно задать при создании StatsClient через настройку, как это делаем в 21-й строке с serverUrl.

2023-09-17 18:07 UTC, z8q approved these changes

2023-09-17 18:07 UTC, z8q commented on stats/client/src/main/java/ru/practicum/stats_client/StatsClient.java
> +    public ResponseEntity<Object> addHit(@Value("${app}") String app, String uri, String ip) {
Имел ввиду, что параметр app мог бы задаваться через настройку, но в конструкторе (как serverUrl), а не в методе

2023-09-17 18:57 UTC, koalannette commented on stats/client/src/main/java/ru/practicum/stats_client/StatsClient.java
> +    public ResponseEntity<Object> addHit(@Value("${app}") String app, String uri, String ip) {
Поняла! Учту это во втором этапе! Спасибо :)

2023-09-17 18:58 UTC, merged