first-iteration main_svc
koalannette/java-explore-with-me pull request #4
Opened 2023-09-29 22:07 UTC by koalannette

2023-09-30 10:18 UTC, z8q requested changes

2023-09-30 10:18 UTC, z8q commented on ewm-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +            return dto.size() > 0 ? ((ViewStatsDto) dto.get(0)).getHits() : 1L;
Получаем ResponseEntity<Object>, из-за чего приходится делать приведение к типу (List<?>), потом к (ViewStatsDto), хотя StatsServerController умеет возвращать ResponseEntity<List<ViewStatsDto>>.
BaseClient после контроллера переводит обратно в Object, что не очень хорошо

2023-10-01 13:44 UTC, koalannette commented on ewm-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +            return dto.size() > 0 ? ((ViewStatsDto) dto.get(0)).getHits() : 1L;
Я почти поняла, как исправить. Пока чуть-чуть запуталась

2023-10-01 20:57 UTC, z8q approved these changes

2023-10-02 17:57 UTC, merged